package com.intecanar.ondiet.data.database

import android.content.Context
import com.intecanar.ondiet.data.database.entities.MyObjectBox

import io.objectbox.BoxStore

object ObjectBox {
    lateinit var boxStore: BoxStore
        private set

    fun init(context: Context) {
        //MyObjectBox is generated by io.objectbox
        boxStore = MyObjectBox.builder()
            .androidContext(context.applicationContext)
            .build()
    }
}